<?php
// Complete D2 Expansion unique and set item reference list.
// quality: 7=unique, 5=set
$grailItems = array(

// ============================================================
// UNIQUE WEAPONS
// ============================================================
array('name'=>'The Gnasher',           'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Deathspade',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Bladebone',             'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Skull Splitter',        'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Rakescar',              'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Axe of Fechmar',        'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Goreshovel',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'The Chieftain',         'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Brainhew',              'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Humongous',             'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Coldkill',              'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Butcher\'s Pupil',      'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Islestrike',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Pompe\'s Wrath',        'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Guardian Naga',         'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Warlord\'s Trust',      'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Spellsteel',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Stormrider',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Boneslayer Blade',      'quality'=>7, 'cat'=>'Axes'),
array('name'=>'The Minataur',          'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Lycander\'s Flank',     'quality'=>7, 'cat'=>'Axes'),
array('name'=>'The Reaper\'s Toll',    'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Cranebeak',             'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Nord\'s Tenderizer',    'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Ethereal Edge',         'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Hellslayer',            'quality'=>7, 'cat'=>'Axes'),
array('name'=>'Messerschmidt\'s Reaver','quality'=>7,'cat'=>'Axes'),
array('name'=>'Executioner\'s Justice','quality'=>7, 'cat'=>'Axes'),

array('name'=>'Rixot\'s Keen',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Blood Crescent',        'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Skewer of Krintiz',     'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Gleamscythe',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Griswold\'s Edge',      'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Hellplague',            'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Culwen\'s Point',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Shadowfang',            'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Soulflay',              'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Kinemil\'s Awl',        'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Blacktongue',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Ripsaw',                'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Patriarch',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Gull',                  'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Diggler',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Jade Tan Do',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Spectral Shard',        'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Dragon Chang',      'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Razortine',             'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Bloodthief',            'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Lance of Yaggai',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Tannr Gorerod',     'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Dimoak\'s Hew',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Steelgoad',             'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Soul Harvest',          'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Battlebranch',      'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Woestave',              'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Grim Reaper',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Atlantean',             'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Crainte Vomir',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Bing Sz Wang',          'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Vile Husk',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Cloudcrack',            'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Todesfaelle Flamme',    'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Swordguard',            'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Hexfire',               'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Blade of Ali Baba',     'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Ginther\'s Rift',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Headstriker',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Plague Bearer',         'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Cauterizor',        'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Djinn Slayer',          'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Spectral Shard',        'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Baranar\'s Star',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Wizardspike',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Doombringer',           'quality'=>7, 'cat'=>'Swords'),
array('name'=>'The Grandfather',       'quality'=>7, 'cat'=>'Swords'),
array('name'=>'Bishibosh\'s Flame',    'quality'=>7, 'cat'=>'Swords'),

array('name'=>'Knell Striker',         'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Crushflange',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Bloodrise',             'quality'=>7, 'cat'=>'Maces'),
array('name'=>'The General\'s Tan Do Li Ga','quality'=>7,'cat'=>'Maces'),
array('name'=>'Ironstone',             'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Bonesnap',              'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Steeldriver',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Felloak',               'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Stoutnail',             'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Stormeye',              'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Darkforce Spawn',       'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Fleshrender',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Sureshrill Frost',      'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Moonfall',              'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Baezil\'s Vortex',      'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Earthshaker',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Bloodtree Stump',       'quality'=>7, 'cat'=>'Maces'),
array('name'=>'The Gavel of Pain',     'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Nord\'s Tenderizer',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Demon Limb',            'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Steelclash',            'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Bane Ash',              'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Serpent Lord',          'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Spire of Lazarus',      'quality'=>7, 'cat'=>'Maces'),
array('name'=>'The Iron Jang Bong',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Razorswitch',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Ribcracker',            'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Chromatic Ire',         'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Warpspear',             'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Skull Collector',       'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Arm of King Leoric',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Blackhand Key',         'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Dark Clan Crusher',     'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Fleshrender',           'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Horizon\'s Tornado',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Stormlash',             'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Earthshifter',          'quality'=>7, 'cat'=>'Maces'),
array('name'=>'The Cranium Basher',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Schaefer\'s Hammer',    'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Astreon\'s Iron Ward',  'quality'=>7, 'cat'=>'Maces'),
array('name'=>'The Fetid Sprinkler',   'quality'=>7, 'cat'=>'Maces'),
array('name'=>'Hand of Blessed Light', 'quality'=>7, 'cat'=>'Maces'),

array('name'=>'Torch of Iro',          'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Maelstrom',             'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Gravenspine',           'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Ume\'s Lament',         'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Carin Shard',           'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Arm of King Leoric',    'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Blackhand Key',         'quality'=>7, 'cat'=>'Staves'),
array('name'=>'The Oculus',            'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Herald of Zakarum',     'quality'=>7, 'cat'=>'Staves'),
array('name'=>'Orb of Destruction',    'quality'=>7, 'cat'=>'Staves'),

array('name'=>'Leadcrow',              'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Ichorsting',            'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Hellcast',              'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Duskdeep',              'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Wizendraw',             'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Hellclap',              'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Blastbark',             'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Skystrike',             'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Raven Claw',            'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Kuko Shakaku',          'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Endlesshail',           'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Whichwild String',      'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Cliffkiller',           'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Magewrath',             'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Goldstrike Arch',       'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Eaglehorn',             'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Widowmaker',            'quality'=>7, 'cat'=>'Bows'),
array('name'=>'Windforce',             'quality'=>7, 'cat'=>'Bows'),

array('name'=>'Gimmershred',           'quality'=>7, 'cat'=>'Throwing'),
array('name'=>'Lacerator',             'quality'=>7, 'cat'=>'Throwing'),
array('name'=>'Windhammer',            'quality'=>7, 'cat'=>'Throwing'),
array('name'=>'Warshrike',             'quality'=>7, 'cat'=>'Throwing'),
array('name'=>'Gargoyle\'s Bite',      'quality'=>7, 'cat'=>'Throwing'),
array('name'=>'Dracul\'s Grasp',       'quality'=>7, 'cat'=>'Throwing'),

array('name'=>'Hone Sundan',           'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Spire of Honor',        'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Demon\'s Arch',         'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Bloodletter',           'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Coldsteel Eye',         'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Bonehew',               'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Ogre Maul',             'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Stone Crusher',         'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Rotting Fissure',       'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Hellrack',              'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Arioc\'s Needle',       'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Steel Shade',           'quality'=>7, 'cat'=>'Polearms'),
array('name'=>'Viperfork',             'quality'=>7, 'cat'=>'Polearms'),

// ============================================================
// UNIQUE ARMOR
// ============================================================
array('name'=>'Greyform',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Blinkbat\'s Form',      'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'The Centurion',         'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Twitchthroe',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Darkglow',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Hawkmail',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Venom Ward',            'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Iceblink',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Boneflesh',             'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Rockfleece',            'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Rattlecage',            'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Goldskin',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Victors Silk',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Heavenly Garb',         'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Pelta Lunata',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Umbral Disk',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Stormchaser',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Tiamat\'s Rebuke',      'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Kerke\'s Sanctuary',    'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Radament\'s Sphere',    'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'The Deflector',         'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Moser\'s Blessed Circle','quality'=>7,'cat'=>'Body Armor'),
array('name'=>'Bverrit Keep',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'The Ward',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'The Torch',             'quality'=>7, 'cat'=>'Body Armor'), // Paladin shield
array('name'=>'Lidless Wall',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Lance Guard',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Skin of the Vipermagi', 'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Skin of the Flayed One','quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Ironpelt',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Spiritforge',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Crow Caw',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Shaftstop',             'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Duriel\'s Shell',       'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Skullder\'s Ire',       'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Guardian Angel',        'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Toothrow',              'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Atma\'s Wail',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Black Hades',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Corpsemourn',           'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Que-Hegan\'s Wisdom',   'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Visceratuant',          'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Mosaic',                'quality'=>7, 'cat'=>'Body Armor'), // claw - miscat, ok
array('name'=>'Cerebus\' Bite',        'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Jalal\'s Mane',         'quality'=>7, 'cat'=>'Body Armor'), // Pelt
array('name'=>'The Spirit Shroud',     'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Skin of the Vipermagi', 'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Ormus\' Robes',         'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Arkaine\'s Valor',      'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Leviathan',             'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Steel Carapace',        'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Tyrael\'s Might',       'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'Griswold\'s Heart',     'quality'=>7, 'cat'=>'Body Armor'),
array('name'=>'The Gladiator\'s Bane', 'quality'=>7, 'cat'=>'Body Armor'),

array('name'=>'Biggin\'s Bonnet',      'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Tarnhelm',              'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Coif of Glory',         'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Duskdeep',              'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Wormskull',             'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Howltusk',              'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Undead Crown',          'quality'=>7, 'cat'=>'Helms'),
array('name'=>'The Face of Horror',    'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Rockstopper',           'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Stealskull',            'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Darksight Helm',        'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Valkyrie Wing',         'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Crown of Thieves',      'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Blackhorn\'s Face',     'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Vampiregaze',           'quality'=>7, 'cat'=>'Helms'),
array('name'=>'The Scalper',           'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Harlequin Crest',       'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Nightwing\'s Veil',     'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Crown of Ages',         'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Andariel\'s Visage',    'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Gaze of Baal',          'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Griffon\'s Eye',        'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Kira\'s Guardian',      'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Giant Skull',           'quality'=>7, 'cat'=>'Helms'),
array('name'=>'Tal Rasha\'s Horadric Crest','quality'=>7,'cat'=>'Helms'),
array('name'=>'Death Mask',            'quality'=>7, 'cat'=>'Helms'),

array('name'=>'Sander\'s Riprap',      'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Goblin Toe',            'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Tearhaunch',            'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Hotspur',               'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Gorefoot',              'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Treads of Cthon',       'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Silkweave',             'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Waterwalk',             'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Albrecht\'s Boots',     'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Infernostride',         'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Aldur\'s Advance',      'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Sandstorm Trek',        'quality'=>7, 'cat'=>'Boots'),
array('name'=>'War Traveler',          'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Gore Rider',            'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Marrowwalk',            'quality'=>7, 'cat'=>'Boots'),
array('name'=>'Eth\'s Tome',           'quality'=>7, 'cat'=>'Boots'),

array('name'=>'The Hand of Broc',      'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Bloodfist',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Chance Guards',         'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Magefist',              'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Frostburn',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Gargoyle\'s Bite',      'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Venom Grip',            'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Gravepalm',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Ghoulhide',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Lava Gout',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Hellmouth',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Dracul\'s Grasp',       'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Soul Drainer',          'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Steelrend',             'quality'=>7, 'cat'=>'Gloves'),
array('name'=>'Trang-Oul\'s Claws',    'quality'=>7, 'cat'=>'Gloves'),

array('name'=>'Lenymo',                'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Snakecord',             'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Nightsmoke',            'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Goldwrap',              'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Bladebuckle',           'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Nos\'eferatu\'s Coil',  'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Razortail',             'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Gloom\'s Trap',         'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Thundergod\'s Vigor',   'quality'=>7, 'cat'=>'Belts'),
array('name'=>'String of Ears',        'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Arachnid Mesh',         'quality'=>7, 'cat'=>'Belts'),
array('name'=>'Verdungo\'s Hearty Cord','quality'=>7,'cat'=>'Belts'),
array('name'=>'Wilhelm\'s Pride',      'quality'=>7, 'cat'=>'Belts'),

// ============================================================
// UNIQUE JEWELRY
// ============================================================
array('name'=>'Nagelring',             'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Manald Heal',           'quality'=>7, 'cat'=>'Rings'),
array('name'=>'The Stone of Jordan',   'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Dwarf Star',            'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Raven Frost',           'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Bul-Kathos\' Wedding Band','quality'=>7,'cat'=>'Rings'),
array('name'=>'Carrion Wind',          'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Nature\'s Peace',       'quality'=>7, 'cat'=>'Rings'),
array('name'=>'Wisp Projector',        'quality'=>7, 'cat'=>'Rings'),

array('name'=>'Nokozan Relic',         'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'The Eye of Etlich',     'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'The Mahim-Oak Curio',   'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Saracen\'s Chance',     'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'The Cat\'s Eye',        'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'The Rising Sun',        'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Crescent Moon',         'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Atma\'s Scarab',        'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Highlord\'s Wrath',     'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Mara\'s Kaleidoscope',  'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Seraph\'s Hymn',        'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Metalgrid',             'quality'=>7, 'cat'=>'Amulets'),
array('name'=>'Tal Rasha\'s Adjudication','quality'=>7,'cat'=>'Amulets'),

// ============================================================
// SET ITEMS
// ============================================================
// Aldur's Watchtower
array('name'=>'Aldur\'s Stony Gaze',   'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Aldur\'s Deception',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Aldur\'s Rhythm',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Aldur\'s Advance',       'quality'=>5, 'cat'=>'Sets'),
// Arcanna's Tricks
array('name'=>'Arcanna\'s Head',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arcanna\'s Flesh',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arcanna\'s Sign',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arcanna\'s Deathwand',   'quality'=>5, 'cat'=>'Sets'),
// Arctic Gear
array('name'=>'Arctic Horn',            'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arctic Furs',            'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arctic Binding',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Arctic Mitts',           'quality'=>5, 'cat'=>'Sets'),
// Bul-Kathos' Children
array('name'=>'Bul-Kathos\' Sacred Charge','quality'=>5,'cat'=>'Sets'),
array('name'=>'Bul-Kathos\' Tribal Guardian','quality'=>5,'cat'=>'Sets'),
// Civerb's Vestments
array('name'=>'Civerb\'s Cudgel',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Civerb\'s Icon',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Civerb\'s Ward',         'quality'=>5, 'cat'=>'Sets'),
// Cleglaw's Brace
array('name'=>'Cleglaw\'s Tooth',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Cleglaw\'s Claw',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Cleglaw\'s Pincers',     'quality'=>5, 'cat'=>'Sets'),
// Cow King's Leathers
array('name'=>'Cow King\'s Horns',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Cow King\'s Hide',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Cow King\'s Hooves',     'quality'=>5, 'cat'=>'Sets'),
// Death's Disguise
array('name'=>'Death\'s Hand',          'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Death\'s Guard',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Death\'s Touch',         'quality'=>5, 'cat'=>'Sets'),
// Griswold's Legacy
array('name'=>'Griswold\'s Valor',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Griswold\'s Heart',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Griswold\'s Redemption', 'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Griswold\'s Honor',      'quality'=>5, 'cat'=>'Sets'),
// Heaven's Brethren
array('name'=>'Haemosu\'s Adamant',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Ondal\'s Almighty',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Whitstan\'s Guard',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Dangoon\'s Teaching',    'quality'=>5, 'cat'=>'Sets'),
// Hsarus' Defense
array('name'=>'Hsarus\' Iron Heel',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Hsarus\' Iron Stay',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Hsarus\' Iron Fist',     'quality'=>5, 'cat'=>'Sets'),
// Hwanin's Majesty
array('name'=>'Hwanin\'s Splendour',    'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Hwanin\'s Refuge',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Hwanin\'s Blessing',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Hwanin\'s Justice',      'quality'=>5, 'cat'=>'Sets'),
// Immortal King
array('name'=>'Immortal King\'s Will',  'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Immortal King\'s Soul Cage','quality'=>5,'cat'=>'Sets'),
array('name'=>'Immortal King\'s Detail','quality'=>5, 'cat'=>'Sets'),
array('name'=>'Immortal King\'s Forge', 'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Immortal King\'s Pillar','quality'=>5, 'cat'=>'Sets'),
array('name'=>'Immortal King\'s Stone Crusher','quality'=>5,'cat'=>'Sets'),
// Infernal Tools
array('name'=>'Infernal Cranium',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Infernal Torch',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Infernal Sign',          'quality'=>5, 'cat'=>'Sets'),
// Isenhart's Armory
array('name'=>'Isenhart\'s Lightbrand', 'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Isenhart\'s Parry',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Isenhart\'s Case',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Isenhart\'s Horns',      'quality'=>5, 'cat'=>'Sets'),
// M'avina's Battle Hymn
array('name'=>'M\'avina\'s True Sight',  'quality'=>5, 'cat'=>'Sets'),
array('name'=>'M\'avina\'s Embrace',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'M\'avina\'s Icy Clutch',  'quality'=>5, 'cat'=>'Sets'),
array('name'=>'M\'avina\'s Tenet',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'M\'avina\'s Caster',      'quality'=>5, 'cat'=>'Sets'),
// Milabrega's Regalia
array('name'=>'Milabrega\'s Orb',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Milabrega\'s Robe',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Milabrega\'s Diadem',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Milabrega\'s Rod',        'quality'=>5, 'cat'=>'Sets'),
// Naj's Ancient Vestige
array('name'=>'Naj\'s Puzzler',          'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Naj\'s Light Plate',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Naj\'s Circlet',          'quality'=>5, 'cat'=>'Sets'),
// Natalya's Odium
array('name'=>'Natalya\'s Totem',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Natalya\'s Shadow',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Natalya\'s Mark',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Natalya\'s Soul',         'quality'=>5, 'cat'=>'Sets'),
// Orphan's Call
array('name'=>'Guillaume\'s Face',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Wilhelm\'s Pride',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Whitstan\'s Guard',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Magnus\' Skin',           'quality'=>5, 'cat'=>'Sets'),
// Sander's Folly
array('name'=>'Sander\'s Paragon',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sander\'s Riprap',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sander\'s Taboo',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sander\'s Superstition',  'quality'=>5, 'cat'=>'Sets'),
// Sazabi's Grand Tribute
array('name'=>'Sazabi\'s Cobalt Redeemer','quality'=>5,'cat'=>'Sets'),
array('name'=>'Sazabi\'s Ghost Liberator','quality'=>5,'cat'=>'Sets'),
array('name'=>'Sazabi\'s Mental Sheath', 'quality'=>5, 'cat'=>'Sets'),
// Sigon's Complete Steel
array('name'=>'Sigon\'s Steel Shade',    'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sigon\'s Wrap',           'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sigon\'s Guard',          'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sigon\'s Gage',           'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sigon\'s Shelter',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Sigon\'s Sabot',          'quality'=>5, 'cat'=>'Sets'),
// Tal Rasha's Wrappings
array('name'=>'Tal Rasha\'s Fire-Spun Cloth','quality'=>5,'cat'=>'Sets'),
array('name'=>'Tal Rasha\'s Adjudication','quality'=>5,'cat'=>'Sets'),
array('name'=>'Tal Rasha\'s Lidless Eye','quality'=>5, 'cat'=>'Sets'),
array('name'=>'Tal Rasha\'s Guardianship','quality'=>5,'cat'=>'Sets'),
array('name'=>'Tal Rasha\'s Horadric Crest','quality'=>5,'cat'=>'Sets'),
// Tancred's Battlegear
array('name'=>'Tancred\'s Crowbill',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Tancred\'s Spine',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Tancred\'s Hobnails',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Tancred\'s Weird',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Tancred\'s Skull',        'quality'=>5, 'cat'=>'Sets'),
// The Disciple
array('name'=>'Credendum',               'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Laying of Hands',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Rite of Passage',         'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Dark Adherent',           'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Telling of Beads',        'quality'=>5, 'cat'=>'Sets'),
// Trang-Oul's Avatar
array('name'=>'Trang-Oul\'s Guise',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Trang-Oul\'s Scales',     'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Trang-Oul\'s Wing',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Trang-Oul\'s Claws',      'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Trang-Oul\'s Girth',      'quality'=>5, 'cat'=>'Sets'),
// Vidala's Rig
array('name'=>'Vidala\'s Barb',          'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Vidala\'s Ambush',        'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Vidala\'s Fetlock',       'quality'=>5, 'cat'=>'Sets'),
array('name'=>'Vidala\'s Snare',         'quality'=>5, 'cat'=>'Sets'),
);
