<?php
// Maps grail item name (lowercase) => NIP base type name (CamelCase, no spaces)
// Generates: [Name] == BaseName && [Flag] != Identified && [Quality] == Unique/Set
$nipBase = array(

// ---- RINGS ----
'nagelring'                       => 'Ring',
'manald heal'                     => 'Ring',
'the stone of jordan'             => 'Ring',
'dwarf star'                      => 'Ring',
'raven frost'                     => 'Ring',
'bul-kathos\' wedding band'       => 'Ring',
'carrion wind'                    => 'Ring',
'nature\'s peace'                 => 'Ring',
'wisp projector'                  => 'Ring',

// ---- AMULETS ----
'nokozan relic'                   => 'Amulet',
'the eye of etlich'               => 'Amulet',
'the mahim-oak curio'             => 'Amulet',
'saracen\'s chance'               => 'Amulet',
'the cat\'s eye'                  => 'Amulet',
'the rising sun'                  => 'Amulet',
'crescent moon'                   => 'Amulet',
'atma\'s scarab'                  => 'Amulet',
'highlord\'s wrath'               => 'Amulet',
'mara\'s kaleidoscope'            => 'Amulet',
'seraph\'s hymn'                  => 'Amulet',
'metalgrid'                       => 'Amulet',
'tal rasha\'s adjudication'       => 'Amulet',

// ---- UNIQUE AXES ----
'the gnasher'                     => 'HandAxe',
'deathspade'                      => 'Axe',
'bladebone'                       => 'DoubleAxe',
'skull splitter'                  => 'MilitaryPick',
'rakescar'                        => 'WarAxe',
'axe of fechmar'                  => 'LargeAxe',
'goreshovel'                      => 'BroadAxe',
'the chieftain'                   => 'BattleAxe',
'brainhew'                        => 'GreatAxe',
'humongous'                       => 'GiantAxe',
'coldkill'                        => 'Hatchet',
'butcher\'s pupil'                => 'Cleaver',
'islestrike'                      => 'TwinAxe',
'pompe\'s wrath'                  => 'Crowbill',
'guardian naga'                   => 'Naga',
'warlord\'s trust'                => 'MilitaryAxe',
'spellsteel'                      => 'BeardedAxe',
'stormrider'                      => 'Tabar',
'boneslayer blade'                => 'GothicAxe',
'the minataur'                    => 'AncientAxe',
'lycander\'s flank'               => 'Tomahawk',
'the reaper\'s toll'              => 'Thresher',
'cranebeak'                       => 'EttinAxe',
'nord\'s tenderizer'              => 'WarSpike',
'ethereal edge'                   => 'BerserkerAxe',
'hellslayer'                      => 'FeralAxe',
'messerschmidt\'s reaver'         => 'SilverEdgedAxe',
'executioner\'s justice'          => 'Decapitator',

// ---- UNIQUE SWORDS ----
'rixot\'s keen'                   => 'ShortSword',
'blood crescent'                  => 'Scimitar',
'skewer of krintiz'               => 'Sabre',
'gleamscythe'                     => 'Falchion',
'griswold\'s edge'                => 'CrystalSword',
'hellplague'                      => 'BroadSword',
'culwen\'s point'                 => 'LongSword',
'shadowfang'                      => 'TwoHandedSword',
'soulflay'                        => 'Claymore',
'kinemil\'s awl'                  => 'GiantSword',
'blacktongue'                     => 'BastardSword',
'ripsaw'                          => 'Flamberge',
'the patriarch'                   => 'GreatSword',
'gull'                            => 'Dagger',
'the diggler'                     => 'Dirk',
'the jade tan do'                 => 'Kris',
'spectral shard'                  => 'Blade',
'the dragon chang'                => 'Spear',
'razortine'                       => 'Trident',
'bloodthief'                      => 'Lance',
'lance of yaggai'                 => 'WingedSpear',
'the tannr gorerod'               => 'HyperionSpear',
'dimoak\'s hew'                   => 'Bardiche',
'steelgoad'                       => 'Voulge',
'soul harvest'                    => 'Scythe',
'the battlebranch'                => 'Poleaxe',
'woestave'                        => 'Halberd',
'the grim reaper'                 => 'WarScythe',
'atlantean'                       => 'AncientSword',
'crainte vomir'                   => 'Espandon',
'bing sz wang'                    => 'DacianFalx',
'the vile husk'                   => 'TuskSword',
'cloudcrack'                      => 'GothicSword',
'todesfaelle flamme'              => 'Zweihander',
'swordguard'                      => 'ExecutionerSword',
'hexfire'                         => 'Shamshir',
'blade of ali baba'               => 'Tulwar',
'ginther\'s rift'                 => 'ElegantBlade',
'headstriker'                     => 'MythicalSword',
'plague bearer'                   => 'HydraEdge',
'the cauterizor'                  => 'ConquestSword',
'djinn slayer'                    => 'PhaseBlade',
'baranar\'s star'                 => 'PhaseBlade',
'wizardspike'                     => 'PhaseBlade',
'doombringer'                     => 'HighlandBlade',
'the grandfather'                 => 'ColossusBlade',
'bishibosh\'s flame'              => 'ColossusSword',

// ---- UNIQUE MACES / CLUBS / WANDS / STAVES ----
'knell striker'                   => 'Club',
'crushflange'                     => 'SpikedClub',
'bloodrise'                       => 'MorningStar',
'the general\'s tan do li ga'     => 'Flail',
'ironstone'                       => 'Mace',
'bonesnap'                        => 'WarHammer',
'steeldriver'                     => 'WarHammer',
'felloak'                         => 'Club',
'stoutnail'                       => 'SpikedClub',
'stormeye'                        => 'MorningStar',
'darkforce spawn'                 => 'BloodlordSkull',
'fleshrender'                     => 'BarbedClub',
'sureshrill frost'                => 'Flail',
'moonfall'                        => 'JaggedStar',
'baezil\'s vortex'                => 'Knout',
'earthshaker'                     => 'BattleHammer',
'bloodtree stump'                 => 'WarClub',
'the gavel of pain'               => 'MarteldeFer',
'demon limb'                      => 'TyrantClub',
'steelclash'                      => 'KiteShield',
'bane ash'                        => 'ShortStaff',
'serpent lord'                    => 'LongStaff',
'spire of lazarus'                => 'GnarledStaff',
'the iron jang bong'              => 'WarStaff',
'razorswitch'                     => 'JoStaff',
'ribcracker'                      => 'Quarterstaff',
'chromatic ire'                   => 'CedarStaff',
'warpspear'                       => 'GothicStaff',
'skull collector'                 => 'RuneStaff',
'arm of king leoric'              => 'Polished Wand',
'blackhand key'                   => 'BoneWand',
'dark clan crusher'               => 'OgreMaul',
'horizon\'s tornado'              => 'Scourge',
'stormlash'                       => 'Scourge',
'earthshifter'                    => 'OgreMaul',
'the cranium basher'              => 'ThunderMaul',
'schaefer\'s hammer'              => 'LegendaryMallet',
'astreon\'s iron ward'            => 'DevilStar',
'the fetid sprinkler'             => 'DivineScepter',
'hand of blessed light'           => 'Caduceus',

// ---- UNIQUE STAVES / ORBS ----
'torch of iro'                    => 'ShortStaff',
'maelstrom'                       => 'YewWand',
'gravenspine'                     => 'BoneWand',
'ume\'s lament'                   => 'GrimWand',
'carin shard'                     => 'BattleStaff',
'the oculus'                      => 'SwirlingCrystal',
'herald of zakarum'               => 'GildedShield',
'orb of destruction'              => 'ElderStaff',

// ---- UNIQUE BOWS ----
'leadcrow'                        => 'ShortBow',
'ichorsting'                      => 'HuntersBow',
'hellcast'                        => 'LongBow',
'duskdeep'                        => 'CompositeBow',
'wizendraw'                       => 'ShortBattleBow',
'hellclap'                        => 'LongBattleBow',
'blastbark'                       => 'ShortWarBow',
'skystrike'                       => 'LongWarBow',
'raven claw'                      => 'EdgeBow',
'kuko shakaku'                    => 'RazorBow',
'endlesshail'                     => 'CedarBow',
'whichwild string'                => 'DoubleBow',
'cliffkiller'                     => 'ShortSiegeBow',
'magewrath'                       => 'LargeSiegeBow',
'goldstrike arch'                 => 'RuneBow',
'eaglehorn'                       => 'CrusaderBow',
'widowmaker'                      => 'WardBow',
'windforce'                       => 'HydraBow',

// ---- UNIQUE THROWING ----
'gimmershred'                     => 'FlyingAxe',
'lacerator'                       => 'WingedAxe',
'windhammer'                      => 'WingedClub',
'warshrike'                       => 'WingedKnife',
'gargoyle\'s bite'                => 'WingedHarpoon',
'dracul\'s grasp'                 => 'VampireboneGloves',

// ---- UNIQUE POLEARMS ----
'hone sundan'                     => 'Yari',
'spire of honor'                  => 'LanceJavelin',
'demon\'s arch'                   => 'Balista',
'bloodletter'                     => 'Gladius',
'coldsteel eye'                   => 'Cestus',
'bonehew'                         => 'OgreAxe',
'ogre maul'                       => 'OgreAxe',
'stone crusher'                   => 'OgreMaul',
'rotting fissure'                 => 'ColossusVoulge',
'hellrack'                        => 'ColossusVoulge',
'arioc\'s needle'                 => 'GhostSpear',
'steel shade'                     => 'RuneHelm',
'viperfork'                       => 'MaidenSpear',

// ---- UNIQUE BODY ARMOR ----
'greyform'                        => 'QuiltedArmor',
'blinkbat\'s form'                => 'LeatherArmor',
'the centurion'                   => 'HardLeatherArmor',
'twitchthroe'                     => 'StuddedLeather',
'darkglow'                        => 'RingMail',
'hawkmail'                        => 'ScaleMail',
'venom ward'                      => 'BreastPlate',
'iceblink'                        => 'ChainMail',
'boneflesh'                       => 'SplintMail',
'rockfleece'                      => 'LightPlate',
'rattlecage'                      => 'FieldPlate',
'goldskin'                        => 'GothicPlate',
'victors silk'                    => 'FullPlateMail',
'heavenly garb'                   => 'AncientArmor',
'pelta lunata'                    => 'Buckler',
'umbral disk'                     => 'SmallShield',
'stormchaser'                     => 'LargeShield',
'tiamat\'s rebuke'                => 'DragonShield',
'kerke\'s sanctuary'              => 'TowerShield',
'radament\'s sphere'              => 'GothicShield',
'the deflector'                   => 'RoundShield',
'moser\'s blessed circle'         => 'RoundShield',
'bverrit keep'                    => 'TowerShield',
'the ward'                        => 'AncientShield',
'the torch'                       => 'AncientShield',
'lidless wall'                    => 'GrimShield',
'lance guard'                     => 'Spiked Shield',
'skin of the vipermagi'           => 'SerpentskinArmor',
'skin of the flayed one'          => 'DemonhideArmor',
'ironpelt'                        => 'TrellisedArmor',
'spiritforge'                     => 'LinkedMail',
'crow caw'                        => 'TigerStrike',
'shaftstop'                       => 'MeshArmor',
'duriel\'s shell'                 => 'Cuirass',
'skullder\'s ire'                 => 'RussetArmor',
'guardian angel'                  => 'TempleHelm',
'toothrow'                        => 'SharkskinArmor',
'atma\'s wail'                    => 'EmbossedPlate',
'black hades'                     => 'ChaosArmor',
'corpsemourn'                     => 'OrnateArmor',
'que-hegan\'s wisdom'             => 'LightGauntlets',
'visceratuant'                    => 'Defender',
'mosaic'                          => 'MatriarchalClaw',
'cerebus\' bite'                  => 'WolfHead',
'jalal\'s mane'                   => 'FurredShield',
'the spirit shroud'               => 'GhostArmor',
'ormus\' robes'                   => 'DuskShroud',
'arkaine\'s valor'                => 'BalrogSkin',
'leviathan'                       => 'KrakenShell',
'steel carapace'                  => 'ShadowPlate',
'tyrael\'s might'                 => 'SacredArmor',
'griswold\'s heart'               => 'OrnateArmor',
'the gladiator\'s bane'           => 'WireFleece',

// ---- UNIQUE HELMS ----
'biggin\'s bonnet'                => 'Cap',
'tarnhelm'                        => 'SkullCap',
'coif of glory'                   => 'HelmetHelm',
'wormskull'                       => 'BoneHelm',
'howltusk'                        => 'GreatHelm',
'undead crown'                    => 'Crown',
'the face of horror'              => 'Mask',
'rockstopper'                     => 'Sallet',
'stealskull'                      => 'CasqueHelm',
'darksight helm'                  => 'BascinetHelm',
'valkyrie wing'                   => 'WingedHelm',
'crown of thieves'                => 'GrandCrown',
'blackhorn\'s face'               => 'DeathMask',
'vampiregaze'                     => 'GrimHelm',
'the scalper'                     => 'FangedHelm',
'harlequin crest'                 => 'Shako',
'nightwing\'s veil'               => 'SpiredHelm',
'crown of ages'                   => 'Corona',
'andariel\'s visage'              => 'Demonhead',
'gaze of baal'                    => 'SacredTarge',
'griffon\'s eye'                  => 'Diadem',
'kira\'s guardian'                => 'Tiara',
'giant skull'                     => 'BoneVisage',
'tal rasha\'s horadric crest'     => 'DeathMask',
'death mask'                      => 'DeathMask',

// ---- UNIQUE BOOTS ----
'sander\'s riprap'                => 'Boots',
'goblin toe'                      => 'LightPlatedBoots',
'tearhaunch'                      => 'Greaves',
'hotspur'                         => 'Boots',
'gorefoot'                        => 'HeavyBoots',
'treads of cthon'                 => 'ChainBoots',
'silkweave'                       => 'MeshBoots',
'waterwalk'                       => 'SharkskinBoots',
'albrecht\'s boots'               => 'HeavyBoots',
'infernostride'                   => 'DemonhideBoots',
'aldur\'s advance'                => 'BattleBoots',
'sandstorm trek'                  => 'BoneweaveBoots',
'war traveler'                    => 'BattleBoots',
'gore rider'                      => 'WarBoots',
'marrowwalk'                      => 'BoneweaveBoots',
'eth\'s tome'                     => 'MeshBoots',

// ---- UNIQUE GLOVES ----
'the hand of broc'                => 'LeatherGloves',
'bloodfist'                       => 'HeavyGloves',
'chance guards'                   => 'ChainGloves',
'magefist'                        => 'LightGauntlets',
'frostburn'                       => 'HeavyGauntlets',
'venom grip'                      => 'DemonhideGloves',
'gravepalm'                       => 'SharkskinGloves',
'ghoulhide'                       => 'HeavyBracers',
'lava gout'                       => 'BattleGauntlets',
'hellmouth'                       => 'WarGauntlets',
'dracul\'s grasp'                 => 'VampireboneGloves',
'soul drainer'                    => 'VampirefangBelt',
'steelrend'                       => 'OgreGauntlets',
'trang-oul\'s claws'              => 'TrangOulsClaws',

// ---- UNIQUE BELTS ----
'lenymo'                          => 'Sash',
'snakecord'                       => 'LightBelt',
'nightsmoke'                      => 'Belt',
'goldwrap'                        => 'HeavyBelt',
'bladebuckle'                     => 'PlateBelt',
'nos\'eferatu\'s coil'            => 'SharkskinBelt',
'razortail'                       => 'MeshBelt',
'gloom\'s trap'                   => 'BattleBelt',
'thundergod\'s vigor'             => 'WarBelt',
'string of ears'                  => 'DemonhideSash',
'arachnid mesh'                   => 'SpiderwebSash',
'verdungo\'s hearty cord'         => 'MithrilCoil',
'wilhelm\'s pride'                => 'BattleBelt',

// ---- SET ITEMS (use the set piece's actual base type) ----
// Aldur's Watchtower
'aldur\'s stony gaze'             => 'Hunter\'sGuise',
'aldur\'s deception'              => 'SerpentskinArmor',
'aldur\'s rhythm'                 => 'JaggednKnife',
'aldur\'s advance'                => 'BattleBoots',
// Arcanna's Tricks
'arcanna\'s head'                 => 'SkullCap',
'arcanna\'s flesh'                => 'LightPlate',
'arcanna\'s sign'                 => 'Amulet',
'arcanna\'s deathwand'            => 'LongWand',
// Arctic Gear
'arctic horn'                     => 'ShortBow',
'arctic furs'                     => 'QuiltedArmor',
'arctic binding'                  => 'LightBelt',
'arctic mitts'                    => 'HeavyGloves',
// Bul-Kathos' Children
'bul-kathos\' sacred charge'      => 'ColossussBlade',
'bul-kathos\' tribal guardian'    => 'MilitaryPick',
// Civerb's Vestments
'civerb\'s cudgel'                => 'GrandScepter',
'civerb\'s icon'                  => 'Amulet',
'civerb\'s ward'                  => 'LargeShield',
// Cleglaw's Brace
'cleglaw\'s tooth'                => 'ShortSword',
'cleglaw\'s claw'                 => 'SmallShield',
'cleglaw\'s pincers'              => 'ChainGloves',
// Cow King's Leathers
'cow king\'s horns'               => 'WarHat',
'cow king\'s hide'                => 'StuddedLeather',
'cow king\'s hooves'              => 'HeavyBoots',
// Death's Disguise
'death\'s hand'                   => 'LeatherGloves',
'death\'s guard'                  => 'Sash',
'death\'s touch'                  => 'WarSword',
// Griswold's Legacy
'griswold\'s valor'               => 'Corona',
'griswold\'s heart'               => 'OrnateArmor',
'griswold\'s redemption'          => 'Caduceus',
'griswold\'s honor'               => 'Vortex Shield',
// Heaven's Brethren
'haemosu\'s adamant'              => 'Cuirass',
'ondal\'s almighty'               => 'ElderStaff',
'whitstan\'s guard'               => 'RoundShield',
'dangoon\'s teaching'             => 'ThunderMaul',
// Hsarus' Defense
'hsarus\' iron heel'              => 'ChainBoots',
'hsarus\' iron stay'              => 'Belt',
'hsarus\' iron fist'              => 'Buckler',
// Hwanin's Majesty
'hwanin\'s splendour'             => 'LoricatedMail',
'hwanin\'s refuge'                => 'TowerShield',
'hwanin\'s blessing'              => 'Belt',
'hwanin\'s justice'               => 'Bill',
// Immortal King
'immortal king\'s will'           => 'AvengersGuard',
'immortal king\'s soul cage'      => 'SacredArmor',
'immortal king\'s detail'         => 'WarBelt',
'immortal king\'s forge'          => 'WarGauntlets',
'immortal king\'s pillar'         => 'WarBoots',
'immortal king\'s stone crusher'  => 'OgreMaul',
// Infernal Tools
'infernal cranium'                => 'SkullCap',
'infernal torch'                  => 'GnarledStaff',
'infernal sign'                   => 'LightBelt',
// Isenhart's Armory
'isenhart\'s lightbrand'          => 'BroadSword',
'isenhart\'s parry'               => 'GothicShield',
'isenhart\'s case'                => 'BreastPlate',
'isenhart\'s horns'               => 'FullHelm',
// M'avina's Battle Hymn
'm\'avina\'s true sight'          => 'DiamondBow',
'm\'avina\'s embrace'             => 'KrakenShell',
'm\'avina\'s icy clutch'          => 'BattleGauntlets',
'm\'avina\'s tenet'               => 'SharkskinBelt',
'm\'avina\'s caster'              => 'CeremonialBow',
// Milabrega's Regalia
'milabrega\'s orb'                => 'KiteShield',
'milabrega\'s robe'               => 'AncientArmor',
'milabrega\'s diadem'             => 'Crown',
'milabrega\'s rod'                => 'RoyalScepter',
// Naj's Ancient Vestige
'naj\'s puzzler'                  => 'ElderStaff',
'naj\'s light plate'              => 'LoricatedMail',
'naj\'s circlet'                  => 'Circlet',
// Natalya's Odium
'natalya\'s totem'                => 'GrimHelm',
'natalya\'s shadow'               => 'LoriquatedMail',
'natalya\'s mark'                 => 'Scissors Suwayyah',
'natalya\'s soul'                 => 'MeshBoots',
// Orphan's Call
'guillaume\'s face'               => 'WingedHelm',
'whitstan\'s guard'               => 'RoundShield',
'magnus\' skin'                   => 'SharkskinGloves',
// Sander's Folly
'sander\'s paragon'               => 'SkullCap',
'sander\'s riprap'                => 'HeavyBoots',
'sander\'s taboo'                 => 'HeavyGloves',
'sander\'s superstition'          => 'BoneWand',
// Sazabi's Grand Tribute
'sazabi\'s cobalt redeemer'       => 'CrypticSword',
'sazabi\'s ghost liberator'       => 'BalrogSkin',
'sazabi\'s mental sheath'         => 'BascinetHelm',
// Sigon's Complete Steel
'sigon\'s steel shade'            => 'GreatHelm',
'sigon\'s wrap'                   => 'PlatedBelt',
'sigon\'s guard'                  => 'TowerShield',
'sigon\'s gage'                   => 'Gauntlets',
'sigon\'s shelter'                => 'TempleHelm',
'sigon\'s sabot'                  => 'Greaves',
// Tal Rasha's Wrappings
'tal rasha\'s fire-spun cloth'    => 'LacqueredPlate',
'tal rasha\'s lidless eye'        => 'SwirlingCrystal',
'tal rasha\'s guardianship'       => 'LacqueredPlate',
'tal rasha\'s horadric crest'     => 'DeathMask',
// Tancred's Battlegear
'tancred\'s crowbill'             => 'MilitaryPick',
'tancred\'s spine'                => 'FullPlateMail',
'tancred\'s hobnails'             => 'Boots',
'tancred\'s weird'                => 'Amulet',
'tancred\'s skull'                => 'SkullCap',
// The Disciple
'credendum'                       => 'MithrilCoil',
'laying of hands'                 => 'BrambledMitts',
'rite of passage'                 => 'DemonhideBoots',
'dark adherent'                   => 'DemonhideArmor',
'telling of beads'                => 'Amulet',
// Trang-Oul's Avatar
'trang-oul\'s guise'              => 'CantorTrophy',
'trang-oul\'s scales'             => 'ChaosArmor',
'trang-oul\'s wing'               => 'BoneShield',
'trang-oul\'s claws'              => 'TrangOulsClaws',
'trang-oul\'s girth'              => 'TrangOulsGirth',
// Vidala's Rig
'vidala\'s barb'                  => 'LongBattleBow',
'vidala\'s ambush'                => 'LeatherArmor',
'vidala\'s fetlock'               => 'LightPlatedBoots',
'vidala\'s snare'                 => 'Amulet',
);

// Full NIP lines for items that share a base type and need stats to differentiate.
// These take priority over $nipBase. No comment — grail.php appends // ItemName.
$nipFull = array(

// ---- UNIQUE RINGS (all share base Ring) ----
'nagelring'                  => '[Name] == Ring && [Quality] == Unique # [ItemMagicBonus] == 30',
'the stone of jordan'        => '[Name] == Ring && [Quality] == Unique # [itemmaxmanapercent] == 25',
'bul-kathos\' wedding band'  => '[Name] == Ring && [Quality] == Unique # [maxstamina] == 50 && [lifeleech] >= 3',
'wisp projector'             => '[Name] == Ring && [Quality] == Unique # [itemabsorblightpercent] >= 20 || [itemmagicbonus] >= 20 && [itemabsorblightpercent] >= 10',
'raven frost'                => '[Name] == Ring && [Quality] == Unique # [dexterity] == 20 && [tohit] >= 150',
'dwarf star'                 => '[Name] == Ring && [Quality] == Unique # [maxhp] == 40 && [magicdamagereduction] == 15',
'manald heal'                => '[Name] == Ring && [Quality] == Unique # [ManaregenRate] == 20',
'carrion wind'               => '[Name] == Ring && [Quality] == Unique # [poisonlength] >= 200 && [lifeleech] >= 6',
'nature\'s peace'            => '[Name] == Ring && [Quality] == Unique # [DamageResist] >= 7 && [ItemDamageReduced] >= 3',

// ---- UNIQUE AMULETS (all share base Amulet) ----
'mara\'s kaleidoscope'       => '[Name] == Amulet && [Quality] == Unique # [strength] == 5 && [fireresist] >= 28',
'highlord\'s wrath'          => '[Name] == Amulet && [Quality] == Unique # [lightresist] == 35',
'the cat\'s eye'             => '[Name] == Amulet && [Quality] == Unique # [dexterity] == 25',
'metalgrid'                  => '[Name] == Amulet && [Quality] == Unique # [tohit] >= 450 && [plusdefense] >= 350 && [fireresist] >= 35',
'nokozan relic'              => '[Name] == Amulet && [Quality] == Unique # [fireresist] == 50 && [tohit] >= 35',
'the eye of etlich'          => '[Name] == Amulet && [Quality] == Unique # [lifeleech] >= 3 && [lightradius] >= 3',
'the mahim-oak curio'        => '[Name] == Amulet && [Quality] == Unique # [strength] == 5 && [dexterity] == 5',
'saracen\'s chance'          => '[Name] == Amulet && [Quality] == Unique # [fireresist] == 15 && [coldresist] == 15',
'the rising sun'             => '[Name] == Amulet && [Quality] == Unique # [fireabsorbpercent] >= 3',
'crescent moon'              => '[Name] == Amulet && [Quality] == Unique # [itemabsorblight] >= 10',
'atma\'s scarab'             => '[Name] == Amulet && [Quality] == Unique # [itemdemonamp] >= 1',
'seraph\'s hymn'             => '[Name] == Amulet && [Quality] == Unique # [ItemAllSkills] == 2 && [itemdemonresist] >= 2',
'tal rasha\'s adjudication'  => '[Name] == Amulet && [Quality] == Unique # [SorceressSkills] == 2',

// ---- BOOTS that share BattleBoots base (War Traveler + Aldur's Advance) ----
'war traveler'               => '[Name] == BattleBoots && [Flag] != Identified && [Quality] == Unique',
'aldur\'s advance'           => '[Name] == BattleBoots && [Flag] != Identified && [Quality] == Set',

// ---- BOOTS that share BoneweaveBoots base (Sandstorm Trek + Marrowwalk) ----
'sandstorm trek'             => '[Name] == BoneweaveBoots && [Flag] != Identified && [Quality] == Unique',
'marrowwalk'                 => '[Name] == BoneweaveBoots && [Flag] != Identified && [Quality] == Unique',

);
